<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <OutputType>Library</OutputType>
        <LocalRefsDir Condition="Exists('..\Refs')">..\Refs</LocalRefsDir>
        <BeatSaberDir>$(LocalRefsDir)</BeatSaberDir>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <Copyright>Copyright © 2023</Copyright>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ReeCamera.Tests" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <WarningLevel>3</WarningLevel>
    </PropertyGroup>

    <!--  SYSTEM REFERENCES  -->
    <ItemGroup>
        <Reference Include="System" />
        <Reference Include="System.Core" />
        <Reference Include="System.Xml.Linq" />
        <Reference Include="System.Data.DataSetExtensions" />
        <Reference Include="System.Data" />
        <Reference Include="System.Xml" />
    </ItemGroup>

    <!--  UNITY REFERENCES  -->
    <ItemGroup>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Unity.TextMeshPro.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Mathematics">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Unity.Mathematics.dll</HintPath>
        </Reference>
    </ItemGroup>

    <!--  HM REFERENCES  -->
    <ItemGroup>
        <Reference Include="Main" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Main.dll</HintPath>
        </Reference>
        <Reference Include="HMLib">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\HMLib.dll</HintPath>
        </Reference>
        <Reference Include="HMUI">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\HMUI.dll</HintPath>
        </Reference>
        <Reference Include="BeatSaber.ViewSystem" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.ViewSystem.dll</HintPath>
        </Reference>
        <Reference Include="HMRendering" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\HMRendering.dll</HintPath>
        </Reference>
        <Reference Include="GameplayCore" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\GameplayCore.dll</HintPath>
        </Reference>
        <Reference Include="BGLib.UnityExtension" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BGLib.UnityExtension.dll</HintPath>
        </Reference>
        <Reference Include="BeatSaber.GameSettings" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.GameSettings.dll</HintPath>
        </Reference>
        <Reference Include="BeatSaber.Settings" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.Settings.dll</HintPath>
        </Reference>
        <Reference Include="BeatSaber.BeatmapEditor" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.BeatmapEditor.dll</HintPath>
        </Reference>
        <Reference Include="VRUI" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\VRUI.dll</HintPath>
        </Reference>
        <Reference Include="VRUI.Interfaces">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\VRUI.Interfaces.dll</HintPath>
        </Reference>
    </ItemGroup>

    <!--  MODS/LIBS REFERENCES  -->
    <ItemGroup>
        <Reference Include="IPA.Loader">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\IPA.Loader.dll</HintPath>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>$(BeatSaberDir)\Libs\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="Zenject" publicize="true">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Zenject.dll</HintPath>
        </Reference>
        <Reference Include="Zenject-usage">
            <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\Zenject-usage.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(BeatSaberDir)\Libs\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="SiraUtil">
            <HintPath>$(BeatSaberDir)\Plugins\SiraUtil.dll</HintPath>
        </Reference>
        <Reference Include="BSML">
            <HintPath>$(BeatSaberDir)\Plugins\BSML.dll</HintPath>
        </Reference>
        <Reference Include="CameraUtils">
            <HintPath>$(BeatSaberDir)\Plugins\CameraUtils.dll</HintPath>
        </Reference>
    </ItemGroup>

    <!--  EMBEDDED RESOURCES INCLUDE  -->
    <ItemGroup>
        <EmbeddedResource Include="9_Resources\BSML\**\*.bsml"/>
        <EmbeddedResource Include="9_Resources\AssetBundles\asset_bundle"/>
        <EmbeddedResource Include="9_Resources\AssetBundles\camera_preview"/>
        <EmbeddedResource Include="9_Resources\Plugins\KlakSpout.dll"/>
        <EmbeddedResource Include="manifest.json"/>
    </ItemGroup>

    <!--  BeatSaberModdingTools  -->
    <ItemGroup>
        <PackageReference Include="BeatSaberModdingTools.Tasks">
            <Version>1.4.3</Version>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="9_Resources\BSML\Inputs\" />
      <Folder Include="UI\Inputs\" />
    </ItemGroup>
</Project>
